export function generateGrievanceDraft(params: {
  policyNumber?: string | null
  insurerName?: string | null
  claimantName: string
  claimRef?: string | null
  reason: string
  amount?: number | null
  date?: string | null
  clauseExcerpt?: string | null
}): { subject: string; body: string } {
  const date = params.date || new Date().toLocaleDateString('en-IN')
  const policyNum = params.policyNumber || '[Policy Number]'
  const insurer = params.insurerName || '[Insurer Name]'
  const claimRef = params.claimRef || '[Claim Reference Number]'

  const subject = `Grievance: Claim rejection / delay for ${params.claimantName} — Policy ${policyNum}`

  const body = [
    `To,`,
    `The Grievance Redressal Officer,`,
    `${insurer}`,
    `[Insurer Address]`,
    ``,
    `Date: ${date}`,
    ``,
    `Subject: ${subject}`,
    ``,
    `Respected Sir/Madam,`,
    ``,
    `I, ${params.claimantName}, am holding a Health Insurance Policy (No: ${policyNum}) with your esteemed company.`,
    ``,
    `I filed a claim (Ref: ${claimRef}) on ${params.date || '[Date of claim]'} which was ${params.reason}.`,
    params.amount ? `The claim amount involved is ₹${params.amount.toLocaleString('en-IN')}.` : '',
    ``,
    params.clauseExcerpt
      ? `The policy clause cited for this decision states:\n"${params.clauseExcerpt}"\n`
      : '',
    ``,
    `I believe this decision is not in line with the policy terms as represented to me at the time of purchase. I request you to kindly review this matter at the earliest and provide a resolution.`,
    ``,
    `I have attached the relevant policy documents and claim correspondence for your reference.`,
    ``,
    `Thanking you,`,
    `${params.claimantName}`,
    `Policy No: ${policyNum}`,
    `Phone: [Your Phone Number]`,
    `Email: [Your Email Address]`,
    ``,
    `---`,
    `This draft was generated by PolicyLens (policy-lens.app). It is a user-editable template, not a filed document. Please review and send at your discretion.`,
  ].filter(Boolean).join('\n')

  return { subject, body }
}