import { describe, test, expect } from 'vitest';
import { generateGrievanceDraft } from '../index.js';

describe('generateGrievanceDraft', () => {
  test('generates a draft with all fields', () => {
    const draft = generateGrievanceDraft({
      policyNumber: 'POL-12345',
      insurerName: 'ABC Insurance',
      claimantName: 'Ravi Sharma',
      reason: 'rejected citing pre-existing condition waiting period',
      amount: 150000,
      date: '15/06/2025',
      clauseExcerpt: 'Pre-existing diseases shall be covered after a waiting period of 48 months.',
    });
    expect(draft.subject).toContain('Grievance');
    expect(draft.subject).toContain('Ravi Sharma');
    expect(draft.subject).toContain('POL-12345');
    expect(draft.body).toContain('ABC Insurance');
    expect(draft.body).toContain('Ravi Sharma');
    expect(draft.body).toContain('₹1,50,000');
    expect(draft.body).toContain('15/06/2025');
    expect(draft.body).toContain('48 months');
    expect(draft.body).not.toContain('undefined');
  });

  test('works with minimal fields', () => {
    const draft = generateGrievanceDraft({
      claimantName: 'Priya Patel',
      reason: 'delayed beyond 30 days',
    });
    expect(draft.subject).toContain('Priya Patel');
    expect(draft.body).toContain('Priya Patel');
    expect(draft.body).toContain('[Policy Number]');
    expect(draft.body).toContain('[Insurer Name]');
  });

  test('includes the "not auto-submitted" disclaimer', () => {
    const draft = generateGrievanceDraft({
      claimantName: 'Test User',
      reason: 'test reason',
    });
    expect(draft.body).toContain('This draft was generated by PolicyLens');
    expect(draft.body).toContain('not a filed document');
  });

  test('handles null values gracefully', () => {
    const draft = generateGrievanceDraft({
      policyNumber: null,
      insurerName: null,
      claimantName: 'Test User',
      reason: 'test',
      amount: null,
      date: null,
      clauseExcerpt: null,
    });
    expect(draft.body).toContain('[Policy Number]');
    expect(draft.body).toContain('[Insurer Name]');
    expect(draft.body).not.toContain('null');
  });
});