import { useState } from 'react'

const STAMP_NAMES = {
  RECOMMENDED: { label: 'Recommended', color: 'bg-neem text-white' },
  HIGH_RISK: { label: 'High Risk', color: 'bg-sindoor text-white' },
  READ_WITH_CAUTION: { label: 'Read with Caution', color: 'bg-yellow-400 text-black' },
  CONSUMER_FRIENDLY: { label: 'Consumer Friendly', color: 'bg-neem text-white' },
  HAS_RESTORATION: { label: 'Has Restoration', color: 'bg-stamp-navy text-white' },
  HAS_CO_PAY: { label: 'Has Co-Pay', color: 'bg-sindoor text-white' },
  STRONG_SETTLEMENT_RATIO: { label: 'Strong Settlement Ratio', color: 'bg-neem text-white' },
  LOW_SETTLEMENT_RATIO: { label: 'Low Settlement Ratio', color: 'bg-sindoor text-white' },
}

function ReportCardPrintView({ card, documentId }) {
  const scoreColor = card.score >= 70 ? 'text-neem' : card.score >= 40 ? 'text-turmeric' : 'text-sindoor'

  return (
    <div className="bg-white p-8 rounded-xl border-2 border-ledger-indigo/20 print:p-6" id={`report-card-${documentId}`}>
      {/* Header */}
      <div className="text-center border-b-2 border-ledger-indigo/10 pb-4 mb-4">
        <div className="font-serif-custom text-2xl font-bold text-stamp-navy">PolicyLens Report Card</div>
        <div className="text-xs text-ledger-indigo/50 mt-1">{new Date(card.reportGeneratedAt).toLocaleDateString('en-IN')}</div>
        {card.policyInfo.insurerName && (
          <div className="text-sm text-ledger-indigo/60 mt-1">{card.policyInfo.insurerName}</div>
        )}
      </div>

      {/* Score */}
      <div className="text-center mb-6">
        <div className={`font-mono-custom text-7xl font-bold ${scoreColor}`}>{card.score}</div>
        <div className="text-sm text-ledger-indigo/50">out of 100</div>
      </div>

      {/* Stamps */}
      {card.stamps.length > 0 && (
        <div className="flex flex-wrap justify-center gap-2 mb-6">
          {card.stamps.map((stamp) => {
            const s = STAMP_NAMES[stamp] || { label: stamp, color: 'bg-kraft text-ledger-indigo/60' }
            return (
              <span key={stamp} className={`px-3 py-1 rounded-full text-xs font-bold ${s.color}`}>
                {s.label}
              </span>
            )
          })}
        </div>
      )}

      {/* Settlement Ratio */}
      {card.settlementRatio !== null && (
        <div className="text-center mb-6">
          <span className="inline-flex items-center gap-1.5 text-[10px] uppercase tracking-wider font-semibold px-2 py-0.5 rounded border border-stamp-navy/20 text-stamp-navy/70 bg-stamp-navy/5">
            <span className="w-1.5 h-1.5 rounded-full bg-stamp-navy/40" />
            Settlement Ratio: {card.settlementRatio}%
          </span>
        </div>
      )}

      {/* Top Flags */}
      <div className="space-y-2 mb-6">
        <div className="text-sm font-semibold text-ledger-indigo/70 border-b border-kraft pb-1">Key Findings</div>
        {card.topFlags.map((flag) => (
          <div key={flag.ruleId} className="text-xs text-ledger-indigo/60 pl-2 border-l-2 border-kraft py-1">
            <span className={`font-semibold ${flag.type === 'red' ? 'text-sindoor' : flag.type === 'green' ? 'text-neem' : 'text-turmeric'}`}>
              [{flag.ruleId}]
            </span>{' '}
            {flag.simplifiedExplanation}
          </div>
        ))}
      </div>

      {/* All flags */}
      <div className="text-[10px] text-ledger-indigo/40 text-center border-t border-kraft pt-3">
        Generated by PolicyLens — Not financial advice · Based on IRDAI reference data
      </div>
    </div>
  )
}

export function ReportCard({ documentId }) {
  const [card, setCard] = useState(null)
  const [loading, setLoading] = useState(false)

  if (!documentId) return null

  const fetchCard = async () => {
    setLoading(true)
    try {
      const res = await fetch(`/api/report-card/${documentId}`)
      const data = await res.json()
      if (data.success) setCard(data.reportCard)
    } catch (err) {
      console.error('Failed to fetch report card:', err)
    } finally {
      setLoading(false)
    }
  }

  const shareWhatsApp = () => {
    if (!card) return
    const lines = [
      `📋 PolicyLens Report Card`,
      `Score: ${card.score}/100`,
      card.policyInfo.insurerName ? `Insurer: ${card.policyInfo.insurerName}` : '',
      card.settlementRatio !== null ? `Settlement Ratio: ${card.settlementRatio}%` : '',
      '',
      'Stamps: ' + card.stamps.map(s => STAMP_NAMES[s]?.label || s).join(', '),
      '',
      'Key Findings:',
      ...card.topFlags.map(f => `• [${f.ruleId}] ${f.simplifiedExplanation}`),
      '',
      'Powered by PolicyLens — policy-lens.app',
    ].filter(Boolean).join('\n')

    const url = `https://wa.me/?text=${encodeURIComponent(lines)}`
    window.open(url, '_blank')
  }

  return (
    <div className="bg-ledger-paper border border-kraft rounded-lg p-5">
      <div className="flex items-center justify-between mb-4">
        <div>
          <div className="font-serif-custom text-lg">Report Card</div>
          <p className="text-xs text-ledger-indigo/50">Share your policy health score</p>
        </div>
        {!card && (
          <button
            className="px-4 py-2 bg-ledger-indigo text-ledger-paper rounded-lg text-sm font-medium hover:bg-ledger-indigo/90 transition-colors disabled:opacity-50"
            onClick={fetchCard}
            disabled={loading}
          >
            {loading ? 'Loading...' : 'Generate Report'}
          </button>
        )}
      </div>

      {card && (
        <>
          <ReportCardPrintView card={card} documentId={documentId} />

          <div className="flex gap-3 mt-4">
            <button
              className="flex-1 px-4 py-2.5 text-white rounded-lg text-sm font-bold transition-colors flex items-center justify-center gap-2"
              style={{ backgroundColor: '#25D366' }}
              onClick={shareWhatsApp}
            >
              <span className="text-lg">📱</span> Share on WhatsApp
            </button>
            <button
              className="px-4 py-2.5 bg-kraft text-ledger-indigo/70 rounded-lg text-sm font-medium hover:bg-kraft/70 transition-colors"
              onClick={() => window.print()}
            >
              Print / PDF
            </button>
            <button
              className="px-4 py-2.5 text-sm text-ledger-indigo/40 hover:text-ledger-indigo/60 transition-colors"
              onClick={() => setCard(null)}
            >
              Dismiss
            </button>
          </div>
        </>
      )}
    </div>
  )
}